### PR TITLE
Disable autosize on double click

### PR DESCRIPTION
**Pull request by harupy**
Doc upgrade checklist:

- [ ] random seed is set if using random data
- [ ] file has been moved from `unconverted/x/y.md` to `x/y.md`
- [ ] old boilerplate at top and bottom of file has been removed
- [ ] Every example is independently runnable and is optimized for short line count
- [ ] no more `plot()` or `iplot()`
- [ ] `graph_objs` has been renamed to `graph_objects`
- [ ] `fig = <something>` call is high up in each example
- [ ] minimal creation of intermediate `trace` objects
- [ ] liberal use of `add_trace` and `update_layout`
- [ ] `fig.show()` at the end of each example
- [ ] `px` example at the top if appropriate
- [ ] minimize usage of hex codes for colors in favour of those in https://github.com/plotly/plotly.py-docs/issues/14

---
https://plot.ly/python/images/#zoom-on-static-images

This PR proposes to disable `autosize` on double click and use only `reset` because `autosize` adds margins around the image.

## Current (example on the doc)
demo-reset

## Proposed (tested on Jupyter)
proposed

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks for your pull request! Could you please add a comment (in the same code cell) explaining that this is for disabling autosize because of unwanted margins, and on another comment line link to https://plot.ly/python/configuration-options/? Then I'll merge :-)

**Comment by harupy** [comment]
@emmanuelle Thanks for the comment! I updated the code.

**Comment by harupy** [comment]
If we don't use the autosize, the dummy scatter trace can be omitted.

**Comment by emmanuelle** [comment]
Thank you very much! Merging :dancer: :-)

**Comment by harupy** [comment]
@emmanuelle Thanks for merging!

What do you think about this?
> If we don't use the autosize, the dummy scatter trace can be omitted.

**Comment by nicolaskruchten** [comment]
It seems like this example will be much nicer/easier when the image trace type comes out :) no more “dummy” traces

**Comment by harupy** [comment]
@nicolaskruchten That'd be great! When will it come out?

I acutally used this feature on this PR (https://github.com/mlflow/mlflow/pull/1934) but it was a bit of pain to specify all the layout options.

**Comment by harupy** [comment]
btw the dummy trace can be removed. I tested the following code on [Binder](https://mybinder.org/v2/gh/plotly/plotly.py-docs/master?filepath=python/images.md) and it worked.

```diff
import plotly.graph_objects as go

# Create figure
fig = go.Figure()

# Constants
img_width = 1600
img_height = 900
scale_factor = 0.5

- Add invisible scatter trace.
- This trace is added to help the autoresize logic work.
- fig.add_trace(
-     go.Scatter(
-         x=[0, img_width * scale_factor],
-         y=[0, img_height * scale_factor],
-         mode="markers",
-         marker_opacity=0
-     )
- )

# Configure axes
fig.update_xaxes(
    visible=False,
    range=[0, img_width * scale_factor]
)

fig.update_yaxes(
    visible=False,
    range=[0, img_height * scale_factor],
    # the scaleanchor attribute ensures that the aspect ratio stays constant
    scaleanchor="x"
)

# Add image
fig.update_layout(
    images=[go.layout.Image(
        x=0,
        sizex=img_width * scale_factor,
        y=img_height * scale_factor,
        sizey=img_height * scale_factor,
        xref="x",
        yref="y",
        opacity=1.0,
        layer="below",
        sizing="stretch",
        source="https://raw.githubusercontent.com/michaelbabyn/plot_data/master/bridge.jpg")]
)

# Configure other layout
fig.update_layout(
    width=img_width * scale_factor,
    height=img_height * scale_factor,
    margin={"l": 0, "r": 0, "t": 0, "b": 0},
)

# Disable the autosize on double click because it adds unwanted margins around the image
# More detail: https://plot.ly/python/configuration-options/
fig.show(config={'doubleClick': 'reset'})
```

**Pull request merged**
