### PR TITLE
Update scipy to the current latest version to suppress FutureWarning

### LINKED ISSUE #148: FutureWarning on the doc
Python `FutureWarning` is displayed on the doc (https://plot.ly/python/images/).

Screen Shot 2019-10-20 at 16 59 29

### PR DESCRIPTION
**Pull request by harupy**
This PR updates `scipy` to the current latest version `1.3.1` ([release history](https://pypi.org/project/scipy/#history)) to resolve #148.

### CODE REVIEW

**Comment by emmanuelle** [comment]
@nicolaskruchten how can we run the CI file even when the branch is not on `plotly.py-docs`? I'll look into it, unless you have a quick answer.

**Comment by harupy** [comment]
The future warning still remains.

https://github.com/plotly/plotly.py-docs/blob/built/2019-07-03-images.html#L423-L426

**Comment by harupy** [comment]
Looks like I misunderstood something. Where can I see the built pages?

**Comment by nicolaskruchten** [comment]
They get uploaded as artifacts in CI I believe. Thanks for looking into this for us :)

**Comment by harupy** [comment]
Screen Shot 2019-10-31 at 22 07 29

**Comment by nicolaskruchten** [comment]
OK so this is working now? the `built` branch only updates once PRs are merged into `master` :)

**Comment by harupy** [comment]
Yes this is working

**Comment by harupy** [comment]
oh, I found another one. This one seems to be from pandas.

https://plot.ly/python/choropleth-maps/

**Comment by harupy** [comment]
One workaround that I came up with is adding the css below to hide `div` that contains warning messages.

```css
div.output_stderr {
  display: none;
}
```

**Comment by nicolaskruchten** [comment]
Thanks for the PR! We should look into that other warning for sure. Really what we should do is have CI grep the HTML output for `Warning` and fail the build if there is one :)

**Pull request merged**
