### PR TITLE
Autodoc for the API

### PR DESCRIPTION
**Pull request by emmanuelle**
This is a very WIP PR, open here for discussion. 

To do

- [ ] decide which functions / classes are to be added to the `__all__` of submodules, and how to populate `__all__` (using the codegen for `graph_objects`? Ping @jonmmease )
- [ ] add this doc build to the Makefile so that the CI can generate it
- [ ] QA on theme and a few sentences of introduction

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
https://github.com/plotly/plotly.py/pull/1802 ideally handles the required __all__ in graph_objects

**Comment by emmanuelle** [comment]
Also, do we want to document submodules of modules? For the submodules of `graph_objects` I added them since we refer to objects in submodules. By the way, it would be great to use the `:class:class_name` syntax in docstrings so that sphinx can create links.

**Comment by nicolaskruchten** [comment]
> do we want to document submodules of modules?

Yes I think so!

>  it would be great to use the :class:class_name syntax

Hmmm yes... Is there a way to coax Sphinx into recognizing the existing `.` format?

**Comment by emmanuelle** [comment]
I've looked into the subsubmodule thing and it will require hacking a template for this, so maybe we don't want this to hold us back.

**Comment by emmanuelle** [comment]
For the review the html pages are available in CircleCI artifacts

**Comment by emmanuelle** [comment]
I think this is now ready for review with the CI part. In the `config.yml` should I replace the test for master with this `apidoc` branch so that we can check that it is deployed correctly?

**Pull request merged**
