### PR TITLE
isosurface doc

### PR DESCRIPTION
**Pull request by emmanuelle**
Doc upgrade checklist:

- [x] random seed is set if using random data
- [x] file has been moved from `unconverted/x/y.md` to `x/y.md`
- [x] old boilerplate at top and bottom of file has been removed
- [x] Every example is independently runnable and is optimized for short line count
- [x] no more `plot()` or `iplot()`
- [x] `graph_objs` has been renamed to `graph_objects`
- [x] `fig = <something>` call is high up in each example
- [x] minimal creation of intermediate `trace` objects
- [x] liberal use of `add_trace` and `update_layout`
- [x] `fig.show()` at the end of each example
- [ ] `px` example at the top if appropriate
- [x] minimize usage of hex codes for colors in favour of those in https://github.com/plotly/plotly.py-docs/issues/14

### CODE REVIEW

**Comment by emmanuelle** [comment]
Addresses https://github.com/plotly/documentation/issues/1491

**Comment by nicolaskruchten** [comment]
Small process note: if you included the text `closes https://github.com/plotly/documentation/issues/1491` in your PR description, then that issue will be automatically closed when the PR is merged.

**Comment by emmanuelle** [comment]
oh great thanks

**Comment by nicolaskruchten** [comment]
💃

**Comment by emmanuelle** [comment]
merging, thanks

**Comment by emmanuelle** [comment]
closes https://github.com/plotly/documentation/issues/1491

**Comment by nicolaskruchten** [comment]
Ah the "closes" thing needs to be in the description at the very top, for the automation to work: https://help.github.com/en/articles/closing-issues-using-keywords

**Pull request merged**
