### PR TITLE
[Fix] Fix typo (G.node -> G.nodes)

### PR DESCRIPTION
**Pull request by rky0930**
Fixing typo in Create Edges example code.  
(G.node -> G.nodes)

Doc upgrade checklist:

- [ ] random seed is set if using random data
- [ ] file has been moved from `unconverted/x/y.md` to `x/y.md`
- [ ] old boilerplate at top and bottom of file has been removed
- [ ] Every example is independently runnable and is optimized for short line count
- [ ] no more `plot()` or `iplot()`
- [ ] `graph_objs` has been renamed to `graph_objects`
- [ ] `fig = <something>` call is high up in each example
- [ ] minimal creation of intermediate `trace` objects
- [ ] liberal use of `add_trace` and `update_layout`
- [ ] `fig.show()` at the end of each example
- [ ] `px` example at the top if appropriate
- [ ] minimize usage of hex codes for colors in favour of those in https://github.com/plotly/plotly.py-docs/issues/14

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks! I’m puzzled about why the build passes before this PR... ?

**Comment by rky0930** [comment]
I'm not sure.
Maybe because the code snippets in docs is not executed during build process.. ?

**Comment by nicolaskruchten** [comment]
They definitely are... maybe it doesn’t enter that loop?

**Comment by nicolaskruchten** [comment]
well, both `G.node` and `G.nodes` work with my version of `networkx` but maybe they just updated or something.

**Comment by nicolaskruchten** [comment]
Thanks for the PR!

**Pull request merged**
