### PR TITLE
document new methods add_shape add_annotation

### PR DESCRIPTION
**Pull request by emmanuelle**
I did not replace all `update_layout(annotations=[...])` by `add_annotation` because I feel like sometimes the `update_layout` syntax is nice for adding a bunch of objects (and it always works when you don't know that the `add_*` methods exist) but I'm open to changing all occurrences.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Works for me! Can we add a similar set of doc updates for `layout.images` please? they just got the same treatment :)

**Comment by nicolaskruchten** [comment]
(changing the base back to `master` as this stuff is already in 4.2)

**Comment by emmanuelle** [comment]
> Works for me! Can we add a similar set of doc updates for layout.images please? they just got the same treatment :)

This is done in #163

**Comment by nicolaskruchten** [comment]
OK great, so let's merge this! 💃

**Pull request merged**
